name: deploy vuepress
on:
    push:
        branches:
            - main

jobs:
    buildVuePress:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm i
            - run: npm run build
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                personal_token: ${{secrets.NALA_REPO_TOKEN }}
                publish_dir: ./build
